#数据源连接信息
spring:
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://127.0.0.1:3306/yun_oa?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
  data:
    redis:
      host: 47.108.180.135
      port: 6379
      password: admin
      database: 0
  security:
    user:
      name: wangyao
      password: 111111
      roles: admin

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:com/wy/yunoa/mapper/*.xml
jwt:
  key: "wangYao"
  expire_time: 30000